<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZEYoaI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZEYoaI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZEYoaI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZEYoaI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMZEYoaI\App_KernelDevDebugContainer([
    'container.build_hash' => 'MZEYoaI',
    'container.build_id' => 'f5851d8f',
    'container.build_time' => 1606857569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZEYoaI');
