<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZhj4cpK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhj4cpK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZhj4cpK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZhj4cpK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZhj4cpK\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zhj4cpK',
    'container.build_id' => '4016dae4',
    'container.build_time' => 1607693199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhj4cpK');
