<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerClxSHBp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerClxSHBp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerClxSHBp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerClxSHBp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerClxSHBp\App_KernelDevDebugContainer([
    'container.build_hash' => 'ClxSHBp',
    'container.build_id' => 'ca5359d5',
    'container.build_time' => 1605169993,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerClxSHBp');
